package com.igo.controller.admin;

import com.igo.IGoApplication;
import com.igo.models.data.Data;
import com.igo.models.fares.Cost;
import com.igo.models.opus.OPUS;
import com.igo.models.payment.Card;
import com.igo.models.ticket.Ticket;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

/**
 * @author mkjodhani
 * @project
 * @since 24/03/23
 */
public class Payment {
    Cost.TYPES paymentFor;
    Cost.PERIOD period;
    int opusID;
    @FXML
    private TextField cardholderName;

    @FXML
    private TextField cardNumber;

    @FXML
    private TextField expirationMonth;

    @FXML
    private TextField expirationYear;
    @FXML
    private TextField cvv;

    @FXML
    private ComboBox<Card.TYPES> cardType;


    public void initialize(){
        cardType.setItems(FXCollections.observableArrayList(Card.TYPES.values()));
    }
    public void setPaymentFor(Cost.TYPES paymentFor) {
        this.paymentFor = paymentFor;
    }

    public void setPeriod(Cost.PERIOD period) {
        this.period = period;
    }

    public void setOpusID(int opusID) {
        this.opusID = opusID;
    }

    private boolean validate(){
        return false;
    }
    public void makePayment(ActionEvent actionEvent) {
        try{
            validate();
            if (paymentFor == Cost.TYPES.TICKET){
                Card card = Card.getCardByDetails(cardNumber.getText(),String.format("%s/%s",expirationMonth.getText(),expirationYear.getText()),Integer.valueOf(cvv.getText()), cardType.getValue());
                if (card == null){
                    IGoApplication.showDialogBox("Error!","Please provide valid information!","One of the field is not correct.");
                    return;
                }
                Ticket ticket = Ticket.generateTicketByCard("H3W",period, card);
                IGoApplication.showDialogBox("Success!","Ticket has been generated successfully!","You can refer the generated by #"+ticket.getTicketId()+".");
                Data.getReference().notifyAllObservers();
            }
            else {
                OPUS opus = Data.getReference().getOpusHashMap().get(opusID);
                opus.recharge(period);
            }
        }catch (Exception e){
            IGoApplication.showDialogBox("Error!","Something went wrong!",e.getMessage());
        }
    }
}
