package com.igo.controller.customer;

import com.igo.IGoApplication;
import com.igo.controller.admin.Payment;
import com.igo.models.data.Data;
import com.igo.models.fares.Cost;
import com.igo.models.payment.Card;
import com.igo.models.ticket.Ticket;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.ChoiceDialog;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.Optional;

/**
 * @author mkjodhani
 * @project
 * @since 22/03/23
 */
public class PurchaseTicket {
    @FXML
    ComboBox<Cost.PERIOD> ticketTypeComboBox;
    @FXML
    TextField price;
    public void initialize(){
        ticketTypeComboBox.getItems().add(Cost.PERIOD.ONE_TRIP);
        ticketTypeComboBox.getItems().add(Cost.PERIOD.TWO_TRIPS);
        ticketTypeComboBox.getItems().add(Cost.PERIOD.ONE_DAY);
        ticketTypeComboBox.getItems().add(Cost.PERIOD.THREE_DAYS);
        ticketTypeComboBox.getItems().add(Cost.PERIOD.UN_LIMITED_WEEKEND);
        ticketTypeComboBox.getItems().add(Cost.PERIOD.GROUP);
    }
    public void purchaseTicket(ActionEvent actionEvent) throws IOException {
        Cost.PERIOD ticketType = ticketTypeComboBox.getValue();
        if (ticketType == null){
            return;
        }
        String paymentOptions[] = { "Cash","Cash less" };
        ChoiceDialog d = new ChoiceDialog(paymentOptions[0], paymentOptions);
        d.setHeaderText("Payment Method");
        d.setHeaderText("Select one of the payment method");
        Optional<String> result = d.showAndWait();
        if ( result.isPresent() )
        {
            if(d.getSelectedItem().equals("Cash")){
                Ticket ticket = Ticket.generateTicketByCash("H3W",ticketType);
                IGoApplication.showDialogBox("Success!","Ticket has been generated successfully!","You can refer the generated by #"+ticket.getTicketId()+".");
                Data.getReference().notifyAllObservers();
            }
            else {
                Stage stage = new Stage();
                FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/com/igo/admin/payment.fxml"));
                Scene scene = new Scene(fxmlLoader.load(), IGoApplication.getWidth(), IGoApplication.getHeight());
                Payment payment = fxmlLoader.getController();
                payment.setPaymentFor(Cost.TYPES.TICKET);
                payment.setPeriod(ticketType);
                stage.setTitle("Payment");
                stage.setScene(scene);
                stage.setResizable(false);
                stage.show();
            }
        }
    }
    public void fetch(ActionEvent actionEvent) {
        Cost.PERIOD ticketType = ticketTypeComboBox.getValue();
        if (ticketType == null){
            return;
        }
        double priceValue =  Cost.getTicketPriceByTimePeriod(ticketType);
        price.setText(String.valueOf(priceValue));
    }
}
